### PR TITLE
Use ImplicitModule instead of LegacyModule.

### LINKED ISSUE #174: Update for new Module Hierarchy
I have some `PeekPokeTester`s for rocket-chip `LazyModuleImp`s. Chisel has refactored what `Module` points to and added a whole hierarchy. I don't really understand what all the different modules are meant to be, but evidently `LazyModuleImp` is not a `Module` (I think it is an `ImplicitModule`?) so I can't use `PeekPokeTester`s on it anymore.

I think the fix for this is simple- wherever we have a `T <: Module` should be replaced with `T <: BaseModule` or `UserModule` or whatever the appropriate `Module` type is. @chick, do you know what the appropriate `Module` class is?

### PR DESCRIPTION
**Pull request by grebe**
Closes #174. Supersedes #176.

`ImplicitModule` has `clock` and `reset`, which chisel testers currently assume exist.

### CODE REVIEW

**Comment by ducky64** [comment]
Wait, the code says its using MultiIOModule (where clock and reset is not guaranteed), and not an ImplicitModule (that has clock and reset)?

**Comment by grebe** [comment]
I believe chisel3.MultiIOModule is the same as chisel3.core.ImplicitModule. Seems wrong to me too.

**Comment by grebe** [comment]
@ducky64 Was on mobile before, [relevant code is here](https://github.com/freechipsproject/chisel3/blob/46553432aaf65cff131e59081d57dabe16c2ab55/src/main/scala/chisel3/package.scala#L425)

**Comment by ducky64** [comment]
Right, derp. chisel3 is multi-IO, and only LegacyModule enforces only having io.
... I should know this, I wrote the code ...
Though this means we should take another look at the Module hierarchu naming.

**Comment by grebe** [comment]
Can someone with the power to do so merge this?

**Pull request merged**
