### PR TITLE
Refactor testers for RawModule instead of Module

### LINKED ISSUE #174: Update for new Module Hierarchy
I have some `PeekPokeTester`s for rocket-chip `LazyModuleImp`s. Chisel has refactored what `Module` points to and added a whole hierarchy. I don't really understand what all the different modules are meant to be, but evidently `LazyModuleImp` is not a `Module` (I think it is an `ImplicitModule`?) so I can't use `PeekPokeTester`s on it anymore.

I think the fix for this is simple- wherever we have a `T <: Module` should be replaced with `T <: BaseModule` or `UserModule` or whatever the appropriate `Module` type is. @chick, do you know what the appropriate `Module` class is?

### PR DESCRIPTION
**Pull request by grebe**
Closes #174

### CODE REVIEW

**Comment by shunshou** [comment]
Just starting to look into similar things--what happens when you have a sequential circuit? How does that get tested? -- Unless you completely don't rely on step anymore?

**Comment by grebe** [comment]
I'm not actually positive what will happen- I suspect it depends on the backend. I think for verilator it looks for a hardcoded signal called clock, not sure what will happen with the interpreter.

I suspect the right thing to do is something like changing `step` to
```
def step(n: Int)(implicit clock: Clock): Unit
```

and the tester will have an implicit clock that it gets based on the type of the module. If the module doesn't have a clock, it should error.

**Comment by grebe** [comment]
I'll just add that my motivation for this is from rocket's `LazyModuleImp` which is a `MultiIOModule` that still has `clock` and `reset`, so I haven't really encountered `step` problems. What sort of situation do you have in mind?

**Comment by shunshou** [comment]
I just kind of want to separate the problem of Multiple IO's from potentially having or not having implicit clock/reset. Can't give you a great reason for doing it... I just am trying to re-use existing tester infrastructure for multi-clock, Intervals. For the May tapeout, to support multi-clock, I had to write a lot of boilerplate code to make my modules compatible... Each module was under 1 clock domain, so for unit testing, I just wanted to feed in the default clock, but when I pieced things together, I used custom clocks... 

In that sense, tester refactor needs to happen to keep up with the crazy amounts of changes going on in main Chisel. .__.

**Comment by grebe** [comment]
Yeah, I agree, that should not be something that's hard to do.

Doing the entire refactor is a really big job, though. The module hierarchy refactor in chisel3 took ~3.5 months to merge; I really hope I don't need to wait that long to test `LazyModule`s with chisel-testers.

**Comment by grebe** [comment]
Superseded by #188

**Pull request closed without merging**
