### PR TITLE
add fsdb support, fix some typo

### PR DESCRIPTION
**Pull request by sequencer**

### CODE REVIEW

**Comment by sequencer** [comment]
Ping

**Comment by chick** [comment]
@grebe I believe you use or can access VCS, wondered if you could just do baseline verify that this fix doesn't break anything obvious.

**Comment by sequencer** [comment]
ping

**Comment by grebe** [comment]
Sorry to respond slowly!

This PR looks pretty reasonable to me, but I am getting a failing test. The failure is
```
[info] - can be done from a multiple edits in a file *** FAILED ***
[info]   "...cale=1ns/1ps -debug_[access+all] -Mdir=top.csrc +vcs..." was not equal to "...cale=1ns/1ps -debug_[pp] -Mdir=top.csrc +vcs..." (ToolChainSpec.scala:149)
```

Is this failure spurious? I don't see how it would be related to this PR.

On an unrelated note, I think we should have a better system for telling the backends how to produce different outputs. I think a list of boolean parameters is not super scalable. Maybe it should be a function that gets passed into the backend? This feedback is more for @chick than @sequencer.

**Comment by sequencer** [comment]
After stage being merged into master. Can we use global annotating to rewrite this options?

**Comment by chick** [comment]
I agree that stage phase will provide a better scalable way to direct backend behavior. I don't have the means to check the vcs behavior. @grebe do you still see the error. It would be nice to get this merged

**Comment by sequencer** [comment]
Emmm, any update for this?
Or we are waiting for iotester2?

**Comment by grebe** [comment]
This can be merged once my fix gets merged in. I [PR'd your repo with a fix](https://github.com/sequencer/chisel-testers/pull/1) to one of the tests that was broken. If you merge that in, I think it should be reflected here and then we'll approve and merge.

**Comment by grebe** [comment]
From reading the manual, it seems debug_pp and debug_access should do the same thing as far as fsdb is concerned. Did you find you needed debug_access for some particular reason?

**Comment by sequencer** [comment]
I currently have no access to the synopsys toolchain, but since 2017.12 all `debug_access` contains `dmptf` for the FSDB generation, so I believe newer version of vcs can handle it with `debug_pp`, but I'm not sure is `debug_pp` ok in some old version?
The difference between all and pp is:
```
debug_access+all -> debug_access+line+class+wn+driver+r+w+cbk+f+fn+thread+cbkd
debug_access+pp -> debug_access+w+cbk+drivers
```
(this information maybe out-of-date)

**Comment by grebe** [comment]
Unless @donggyukim thinks otherwise (who git blame tells me is the originator of debug_pp), I think this change looks good now.

**Comment by colinschmidt** [comment]
I don't care too much about this repo but I imagine there may be some performance impact from adding the extra flags?
I assume we use `debug_pp` because rocket-chip uses it, so if there is a more principled approach on which access types to support then go for it.

**Comment by donggyukim** [comment]
It was for performance. If we don't care too much about performance, I think a new flag is fine.

**Comment by grebe** [comment]
I think long term it would be good to have a mechanism to manage vcs options better, but for now I think this is fine.

**Comment by sequencer** [comment]
ping?

**Pull request merged**
