### PR TITLE
Deprecate main APIs as chisel-iotesters is end-of-life

### PR DESCRIPTION
**Pull request by jackkoenig**

### CODE REVIEW

**Comment by ekiwi** [comment]
Are you going to make a small porting guide? If so, it might be nice to make the URL for that and include it with the deprecation message.

**Comment by jackkoenig** [comment]
> Are you going to make a small porting guide?

I would like to, but yet another thing to do.

> If so, it might be nice to make the URL for that and include it with the deprecation message.

I agree, maybe I can at least get a shim doc up, but this among everything else is delaying my ability to get RC2 out ☹️

**Comment by jackkoenig** [comment]
@ekiwi do you think https://www.chisel-lang.org/chiseltest/#migrating-from-chisel-testers--iotesters is a reasonable link for the meantime and we can either enhance it there or if we add a longer form page, we can link to it from the README?

**Review by ekiwi — APPROVED** [review]
Sound good. Can you add the URL to the deprecation warnings? Then feel free to merge.

**Comment by jackkoenig** [comment]
> Sound good. Can you add the URL to the deprecation warnings? Then feel free to merge.

Done, with the help of https://github.com/freechipsproject/www.chisel-lang.org/pull/221, there's a more stable link (https://www.chisel-lang.org/chiseltest/migrating-from-iotesters) that is not yet live but will be shortly. It currently points to the README as I suggested above, but this redirection scheme means we can change it into a more fleshed out document and the link in the deprecation warnings will still work.

**Comment by ekiwi** [comment]
Thanks Jack!

**Comment by schoeberl** [comment]
Small outreach comment: iotesters is deprecated and the alternative ChiselTest is (still) marked as alpha software. Could ChiselTest grow up to 1.5 and drop the alpha wording?

**Comment by ekiwi** [comment]
> Small outreach comment: iotesters is deprecated and the alternative ChiselTest is (still) marked as alpha software. Could ChiselTest grow up to 1.5 and drop the alpha wording?

I would be happy to drop the mention of "alpha" (which it definitely is not). But if we want to follow strict semantic versioning, we do need to stick with the leading `0` unless we find a maintainer who is willing to guarantee strict backwards compatibility.
We also should try to rename the repository to `chiseltest` and ideally move it to the chips alliance organization.

**Comment by ekiwi** [comment]
@schoeberl I removed the `alpha status` from the repo description and this PR also removes it from the README: https://github.com/ucb-bar/chiseltest/pull/469

**Comment by schoeberl** [comment]
Very good! What is the meaning of a maintainer? We should discuss this next Monday. +1 for the chiseltest rename. And probably move it to chipsalliance. But step by step, I am fine with the first step.

**Pull request merged**
