### PR TITLE
Add support for 2.13

### PR DESCRIPTION
**Pull request by chick**
Add support for 2.13, drop relics from 2.11
- Updated build.sbt
  - Removed `-Xsource:2.11` stuff
  - Update scalaVersion and CrossScalaVersions

- Mostly add a bunch of `toSeq`s where needed
- Created some intermediate `ListMap`s where needed

### CODE REVIEW

**Review by ekiwi — CHANGES_REQUESTED** [review]
Nice work, chick!

Can you please add Scala 2.13 tests to the github actions file: https://github.com/freechipsproject/chisel-testers/blob/master/.github/workflows/test.yml

You can use a test matrix like we do in chiseltest: https://github.com/ucb-bar/chisel-testers2/blob/master/.github/workflows/test.yml#L16

https://github.com/ucb-bar/chisel-testers2/blob/master/.github/workflows/test.yml#L51

**Comment by chick** [comment]
@ekiwi Doesn't the `sbt +test` test 2.12 and 2.13?

**Comment by ekiwi** [comment]
> @ekiwi Doesn't the `sbt +test` test 2.12 and 2.13?

I think it should. The test matrix based solution will be a bit faster, since it will launch two independent VMs that run in parallel. However, for this repo it seems fine to stick with the `+test` option.

**Review by ekiwi — APPROVED** [review]
:ship:

**Pull request merged**
