### PR TITLE
Need sbt-ci-release to publish on PR merge

### PR DESCRIPTION
**Pull request by chick**
missed adding this. should publish on push to master

### CODE REVIEW

**Comment by jackkoenig** [comment]
I would suggest also temporarily altering the publish flow to publish on PRs so you can test this PR, then revert the change before merging.

**Review by ekiwi — APPROVED** [review]
Yolo merge to production! :shipit:

**Comment by ekiwi** [comment]
did not work :(

**Comment by ekiwi** [comment]
Someone needs to add the PGP key and passphrase:
```
     PGP_PASSPHRASE: 
    PGP_SECRET: 
```

**Comment by jackkoenig** [comment]
> did not work :(

Told ya

**Pull request merged**
