### PR TITLE
Set symbol separator for VCS harness - fix #193

### LINKED ISSUE #193: 64ab259 breaks examples.AccumBlackBox_PeekPokeTest_VCS
@ucbjrl commented on 64ab259 that it breaks examples.AccumBlackBox_PeekPokeTest_VCS. I'm creating an issue here- can someone with the power to do so assign it to me?

### PR DESCRIPTION
**Pull request by ucbjrl**
Strip dut name prefix from signal names for VCS
Remove unused imports.

### CODE REVIEW

**Comment by ucbjrl** [comment]
@grebe could you take a look at this?

**Comment by grebe** [comment]
This looks good to me- does it fix up the test? I would probably just figure out how big the prefix is and then drop it (as opposed to a regex), but if this works it might be a little bit less mysterious looking.

**Comment by ucbjrl** [comment]
I was tempted to just drop the length of the prefix, but then figured that would fail if the naming convention changes. My hope is that when this fails as a result of a prefix change, the fix will be slightly more obvious.
And yes, it does fix the test.

**Comment by grebe** [comment]
Good thinking. LGTM

**Pull request merged**
